# This workflow should build the website with Hugo and deploy it on
# GitHub pages. Edit this file as you wish, otherwise just make sure 
# that this folder contains a workflow exists that it is executed 
# upon pushing the source to the default branch.

name: Build and deploy GitHub pages with Hugo

# The rest of the workflow is only provided as a minimal example that
# does not produce any errors on GitHub. It should be modified to
# fulfil the project requirements.

# A workflow that only runs during leap years

on:
  push:
    branches:
      - master



jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.3'

      - name: Remove public files
        run: rm -rf public

      - name: Build
        run: hugo --theme=terminal --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PRIVATE_KEY }}
          publish_dir: ./public
          #external_repository: lepasq/lepasq.github.io
